### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by rugvedkoshiya** [yashghori/GMusic#3]
If there will be inbuilt volume control then it will be better

**Comment by yashghori** [comment]
> HTML snippet

`
        <div class="container">
            <i id="volume_mute" class="material-icons">volume_mute</i>
            <i id="volume_down" class="material-icons volume">volume_down</i>
            <i id="volume_up" class="material-icons volume">volume_up</i>
            <input id="volume" min="0" max="60" type="range" value="30" />
        </div>
`

> CSS snippet
`
 /* Volume control */
.container {
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  margin-top: 12px;
}
#volume_mute {
  display: none;
}
#volume_down {
  display: none;
}
/* for chrome */
#volume {
  background: linear-gradient(to right, var(--pink) 0%, var(--violet) 50%, rgb(224, 222, 222) 50%);
  border-radius: 8px;
  height: 5px;
  width: 100px;
  outline: none;
  transition: background 450ms ease-in;
  -webkit-appearance: none;
}
input[type="range"]::-webkit-slider-thumb {
  -webkit-appearance: none;
  border: none;
  height: 14px;
  width: 14px;
  border-radius: 50%;
  background: linear-gradient(90deg, var(--pink), var(--violet));

}
input[type="range"] {
  -webkit-appearance: none;
  cursor: pointer;
}

/* MOZILA */
input[type="range"]::-moz-range-thumb {
  border: none;
  height: 10px;
  width: 10px;
  border-radius: 50%;
  background: linear-gradient(45deg, var(--pink), var(--violet));
}`

> JS snippet
`
    const Audio = document.querySelector('audio'),
    volume = document.getElementById('volume'),
    volume_mute = document.getElementById('volume_mute'),
    volume_down = document.getElementById('volume_down'),
    volume_up = document.getElementById('volume_up');
// custom music control
volume.addEventListener('change',(e)=>{
    Audio.volume = e.currentTarget.value / 100;
    if (Audio.volume === 0) {
        volume_mute.style.display = 'flex';
        volume_down.style.display = 'none';
        volume_up.style.display = 'none';
    } else if((Audio.volume <= 0.5)){
        volume_mute.style.display = 'none';
        volume_down.style.display = 'flex';
        volume_up.style.display = 'none';
    }else{
        volume_mute.style.display = 'none';
        volume_down.style.display = 'none';
        volume_up.style.display = 'flex';
    }
});

// Volume bar
document.getElementById("volume").oninput = function() {
    var value = (this.value-this.min)/(this.max-this.min)*100
    this.style.background = 'linear-gradient(to right, var(--pink) 0%, var(--violet) ' + value + '%, rgb(224, 222, 222) ' + value + '%, rgb(224, 222, 222) 100%)'
  };
`
