### ISSUE TITLE
Mute song when user click on sound icon

### ISSUE THREAD

**Issue by rugvedkoshiya** [yashghori/GMusic#5]
Mute song when user click on sound icons of volume control
![image](https://user-images.githubusercontent.com/54926339/121862185-3199bc00-cd18-11eb-9fad-197ee788f3cf.png)

**Comment by yashghori** [comment]
DONE !
![image](https://user-images.githubusercontent.com/70617831/121896681-33c34100-cd3f-11eb-92a1-ce79c981e384.png)

**Comment by rugvedkoshiya** [comment]
## Mute music changes volume level
when user mute music and unmute then volume level is changing to default it's must remain same

**Comment by yashghori** [comment]
Now it's perfect !😉
![image](https://user-images.githubusercontent.com/70617831/122165021-3a63cc80-ce95-11eb-9a05-2cfeb59da5fd.png)
